replicaCount: 1

image:
  repository: prajjwalgupta0973/project-service
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

spring:
  profiles:
    active: dev

resources: {}

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  cpuUtilization: 70
  memoryUtilization: 70
ingress:
  enabled: false
serviceAccount:
  create: false