replicaCount: 1

image:
  repository: prajjwalgupta0973/project-service
  tag: latest
  pullPolicy: Always
# metadata:
#   annotations:
#     service.beta.kubernetes.io/aws-load-balancer-type: nlb
#     service.beta.kubernetes.io/aws-load-balancer-internal: "false"
#     service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

spring:
  profiles:
    active: dev

resources:
  requests:
    cpu: 100m #(means: 100m = 0.1 CPU core = 10% of a single CPU core.)
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  cpuUtilization: 70
  memoryUtilization: 70
ingress:
  enabled: false
serviceAccount:
  create: false
db:
 url:
  jdbc:postgresql://database-1.c4bs8igw8ni0.us-east-1.rds.amazonaws.com:5432/postgres?currentSchema=project_db_schema