spring:
  sql:
      init:
        mode: always
        schema-locations: classpath:schema.sql
  application:
    name: employee-service
  
  r2dbc:
    url: r2dbc:postgresql://host.docker.internal:5432/postgres?currentSchema=employee_db
    username: postgres
    password: PrajjwalB4@
#debug: true
logging:
  level:
    io:
      r2dbc:
        postgresql: DEBUG
    org:
      springframework:
        data:
          r2dbc: DEBUG
