spring:
  sql:
      init:
        mode: always
        schema-locations: classpath:schema.sql
  application:
    name: employee-service
  
  r2dbc:
    url: r2dbc:postgresql://testpostgresdbaws.c4bs8igw8ni0.us-east-1.rds.amazonaws.com:5432/postgres?sslMode=require&currentSchema=employee_db
    username: postgres
    password: ${DB_PASSWORD}
#debug: true
logging:
  level:
    io:
      r2dbc:
        postgresql: DEBUG
    org:
      springframework:
        data:
          r2dbc: DEBUG
