spring:
  sql:
      init:
        mode: always
        schema-locations: classpath:schema.sql
  application:
    name: employee-service
  
  r2dbc:
    url: ${db.url}
    username: postgres
    password: ${DB_PASSWORD}
#debug: true
logging:
  level:
    io:
      r2dbc:
        postgresql: DEBUG
    org:
      springframework:
        data:
          r2dbc: DEBUG
