replicaCount: 1

image:
  repository: prajjwalgupta0973/employee-service
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

spring:
  profiles:
    active: dev


resources: {}
nodeSelector: {}
tolerations: []
affinity: []

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
  targetMemoryUtilizationPercentage: 70
ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: employee-service.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
serviceAccount:
  create: false