replicaCount: 1

image:
  repository: prajjwalgupta0973/employee-service
  tag: latest
  pullPolicy: Always
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-internal: "false"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080

spring:
  profiles:
    active: dev

resources:
  requests:
    cpu: 100m #(means: 100m = 0.1 CPU core = 10% of a single CPU core.)
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi
nodeSelector: {}
tolerations: []
affinity: []
ingress:
  enabled: false
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 70

  tls: []
serviceAccount:
  create: false
