spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/postgres?currentSchema=project_db_schema
    username: postgres
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
