spring:
  application:
    name: project-service

  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/postgres?currentSchema=project_db_schema
    username: postgres
    password: PrajjwalB4@
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8083
